### ISSUE TITLE
Problems in metrics calculations

### ISSUE THREAD

**Issue by ZAX130** [muregpro/Baseline-Networks#1]
In metrics.py:
![image](https://github.com/muregpro/Baseline-Networks/assets/43944700/0b3445d9-4352-4e7d-8507-c7c05ac29818)
where `sorted_indices` is not used in the calculation of `dsc_scores_for_robustness` in line 37. This means that the final RDSC calculation does not use the sorted data.

The minimal changes I recommend are as follows:
`dsc_scores_for_robustness = dice_scores_all[0:tf.cast(num_samples_dsc, dtype=tf.int32)]`  =>
`dsc_scores_for_robustness = tf.gather(dice_scores_all, sorted_indices[:tf.cast(num_samples_dsc, dtype=tf.int32)])`
The same problem may also arise in the calculation of RTRE and RTs.

**Comment by ZAX130** [comment]
![image](https://github.com/muregpro/Baseline-Networks/assets/43944700/a89caadc-7d04-4eb3-a00a-058efe4532fc)
Another problem is the calculation of HD95. During the calculation process, the calculation along the batch dimension is not calculated one by one and then averaged, which will lead to inaccurate results.

**Comment by zacbaum** [comment]
Thank you @ZAX130 - we will address these changes.

**Comment by s-sd** [comment]
Thank you @ZAX130 for pointing this out! I will update the metrics to incorporate your suggested changes and will let you know once everything has been updated. :)

**Comment by s-sd** [comment]
@ZAX130 please see updated files with your suggested changes implemented. For HD95, we compute the case-wise HD95 in the `evaluation.py` script, see `while` loop on line `76` which iterates the generator by one sample each time. The `HD95` function in `metric.py` is only intended to be used on one sample at a time. 

Thank you very much again for pointing out these things and hopefully the new changes address your concerns. Let me know if any other questions or suggested changes. :)
